client_config_backend: file
client_config:
    client_id: 363324401009-lcv3phmgqe33mc2n0llcq0urq5s3h5ci.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive